local ChessBoard = {}

ChessBoard.img_bc1 = cc.ui.UIImage.new("bche.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bm1 = cc.ui.UIImage.new("bma.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bx1 = cc.ui.UIImage.new("bxiang.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bs1 = cc.ui.UIImage.new("bshi.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bc2 = cc.ui.UIImage.new("bche.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bm2 = cc.ui.UIImage.new("bma.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bx2 = cc.ui.UIImage.new("bxiang.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bs2 = cc.ui.UIImage.new("bshi.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bj = cc.ui.UIImage.new("bjiang.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bp1 = cc.ui.UIImage.new("bpao.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bp2 = cc.ui.UIImage.new("bpao.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bz1 = cc.ui.UIImage.new("bzu.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bz2 = cc.ui.UIImage.new("bzu.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bz3 = cc.ui.UIImage.new("bzu.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bz4 = cc.ui.UIImage.new("bzu.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_bz5 = cc.ui.UIImage.new("bzu.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rc1 = cc.ui.UIImage.new("rche.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rm1 = cc.ui.UIImage.new("rma.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rx1 = cc.ui.UIImage.new("rxiang.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rs1 = cc.ui.UIImage.new("rshi.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rc2 = cc.ui.UIImage.new("rche.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rm2= cc.ui.UIImage.new("rma.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rx2 = cc.ui.UIImage.new("rxiang.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rs2 = cc.ui.UIImage.new("rshi.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rj = cc.ui.UIImage.new("rshuai.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rp1 = cc.ui.UIImage.new("rpao.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rp2 = cc.ui.UIImage.new("rpao.png")
                -- :align(display.CENTER, display.cx, display.cy)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rz1 = cc.ui.UIImage.new("rbing.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rz2 = cc.ui.UIImage.new("rbing.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rz3 = cc.ui.UIImage.new("rbing.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rz4 = cc.ui.UIImage.new("rbing.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
ChessBoard.img_rz5 = cc.ui.UIImage.new("rbing.png")
                -- :align(display.CENTER, display.cx, 500)
                :setLayoutSize(109, 109)
                :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)

ChessBoard.chessBoard  = {{1,0,0,7,0,0,27,0,0,18},
                            {3,0,5,0,0,0,0,22,0,20},
                            {12,0,0,8,0,0,26,0,0,29},
                            {14,0,0,0,0,0,0,0,0,31},
                            {16,0,0,9,0,0,25,0,0,32},
                            {15,0,0,0,0,0,0,0,0,30},
                            {13,0,0,10,0,0,24,0,0,28},
                            {4,0,6,0,0,0,0,21,0,19},
                            {2,0,0,11,0,0,23,0,0,17},
                            {0,0}}

ChessBoard.img_selected = cc.ui.UIImage.new("selected.png")
                            :align(display.CENTER, 54, 54)
                            :setLayoutSize(109, 109)
                            :setLayoutSizePolicy(display.FIXED_SIZE, display.FIXED_SIZE)
return ChessBoard